
const originalThemeList = [
	"Delay the inevitable",
	"Fragile",
	"Make connections",
	"Mutation",
	"Teleportation",
	"A single resource",
	"Folklore",
	"Shelter",
	"Infestation",
	"Road trip",
	"Tunnels",
	"Overgrown",
	"Out of order",
	"Space is limited",
	"Combine",
	"Garden",
	"Sky pirates",
	"Echoes",
	"You are the power source",
	"Crossroads",
	"Repair",
	"Branching out",
	"Momentum",
	"Strength in numbers",
	"Decay",
	"Treasure Map",
	"Fill the void",
	"Some assembly required",
	"Playing both sides",
	"One use only",
	"Replication",
	"Automation",
	"Layers",
	"Corruption",
	"Color is a mechanic",
	"Overflow",
	"You control the environment, not the character",
	"Leave something behind",
	"Snowball effect",
	"A faithful companion",
	"Become the enemy",
	"Read the manual",
	"Outnumbered",
	"One tool, many purposes",
	"Clockwork",
	"Parasite",
	"Different every time",
	"Mirror",
	"Out of bounds",
	"Unstable",
	"Making connections",
	"One tool, many uses",
	"Decay",
	"On / Off",
	"Delay the inevitable",
	"Keep your distance",
	"Delivery",
	"The environment changes you",
	"Leave something behind",
	"Everything changes at night",
	"3 rules",
	"Replication",
	"Strength in numbers",
	"Summoning",
	"It follows you",
	"One tool, many uses",
	"Summoning",
	"Delay the inevitable",
	"Inconvenient superpowers",
	"Rules can be broken",
	"Delivery",
	"Mutations",
	"Witchcraft",
	"Missing parts",
	"Labyrinth",
	"Ruins",
	"Butterfly effect",
	"Orbital",
	"Making connections",
	"The environment changes you",
	"Out of order",
	"The floor is lava",
	"Keep your distance",
	"Corruption",
	"Switching perspectives",
	"Replication",
	"Decay",
	"Leave something behind",
	"Death is not the end",
	"Everything changes at night",
	"Reflection",
	"Sanctuary",
	"You are the power source",
	"Cartography",
	"Road trip",
	"Control the environment",
	"Mushrooms",
	"First day on the job",
	"Strength in numbers",
	"On / Off",
	"Ghost town",
	"Symbiotic relationships",
	"It follows you",
	"Isolation",
	"Automation",
	"Teleportation",
	"Momentum",
	"Symmetry",
	"3 rules",
	"Dice",
	"Parasite",
	"Overflow",
	"Unstable",
	"Delivery",
	"One time use",
	"Momentum",
	"Rain",
	"Something is missing",
	"Split in two",
	"Fragile",
	"Leave something behind",
	"Expansion",
	"Out of bounds",
	"Instructions unclear",
	"Shoot for the moon",
	"Playing both sides",
	"Clockwork",
	"You are what you eat",
	"Lost signal",
	"Fragmentation",
	"Automation",
	"Generations",
	"Containment",
	"Feed the fire",
	"Deeper and deeper",
	"Supply lines",
	"One tool, many uses",
	"Equilibrium",
	"Stick together",
	"Symmetry",
	"Perspectives",
	"Garden",
	"Corruption",
	"Butterfly effect",
	"Hivemind",
	"Parasite",
	"Choose your poison",
	"Recycling",
	"Reflections",
	"Some assembly required",
	"Shelter",
	"Out of order",
	"Overflow",
	"Summoning",
	"You are the power source",
	"Duplication",
	"You really shouldn't mix those",
	"Public transport",
	"Myths and legends",
	"Hidden world",
	"Never break the chain",
	"Deeper and deeper",
	"Leave something behind",
	"Parasite",
	"Shelter",
	"Expansion",
	"Hidden world",
	"Delivery",
	"You are the power source",
	"Generations",
	"One tool, many uses",
	"Automation",
	"Lost signal",
	"One time use",
	"Containment",
	"Split in two",
	"Summoning",
	"Decay",
	"Layers",
	"Control the world, not the player",
	"Nomad",
	"Connections",
	"Stuck in a loop",
	"Feeding the monster",
	"Delay the inevitable",
	"Contain it",
	"Day and night",
	"Shipwrecked",
	"Clockwork",
	"You can't save them all",
	"Death is not the end",
	"Summoning",
	"The world changes when you are not looking",
	"Day and night",
	"Decay",
	"Overheat",
	"Isolation",
	"Death is not the end",
	"Modular world",
	"Make it grow",
	"Shifting perspectives",
	"Transportation",
	"Summoning",
	"Connections",
	"Parasite",
	"Technical difficulties",
	"Magnetism",
	"Explore the Unknown",
	"Only 3 buttons",
	"Feeding the monster",
	"Contain it",
	"Delay the inevitable",
	"60 seconds to prepare",
	"Wait are we the bad guys?",
	"Strength in numbers",
	"Mythology",
	"Control the world, not the player",
	"1 vs 100",
	"Fragile",
	"Mass production",
	"The butterfly effect",
	"Replaceable parts",
	"Start with everything, end with nothing",
	"Play against yourself",
	"Two worlds",
	"Nomad",
	"Shipwrecked",
	"Clockwork",
	"You can't save them all",
	"Layers",
	"Reflection",
	"Roll the dice",
	"Four seasons",
	"The world changes when you are not looking",
	"Stuck in a loop",
	"Door to anywhere",
	"Automation",
	"You're not supposed to be here",
	"Lack of information",
	"Mutation",
	"Alchemy",
	"Garden",
	"Decay",
	"Turn a violent genre non-violent",
	"An ancient language",
	"Butterfly effect",
	"Déjà vu",
	"1 minute to prepare",
	"Fragile",
	"You are the dungeon",
	"Grow a tree",
	"Side effects",
	"Four elements",
	"Your game has 3 rules, but only one is active at a time",
	"You are the princess waiting to be rescued",
	"Equilibrium",
	"Dreams",
	"Momentum",
	"Sabotage",
	"Echo",
	"You are the power source",
	"Tower offense",
	"Mythology",
	"Fragmentation",
	"Turn a job into a game",
	"Evolve",
	"Replication",
	"You can't save them all",
	"Control two things at once",
	"Stuck in the loop",
	"Déjà vu",
	"Multiple perspectives",
	"Déjà vu",
	"Outdated technology",
	"Magnetism",
	"Malfunction",
	"Ruins",
	"Connections",
	"Automation",
	"Keep it alive",
	"Reflection",
	"Planets",
	"Seasons",
	"An abandoned world",
	"Protect the king",
	"Shelter",
	"Inconvenient superpowers",
	"Delayed effects",
	"Dreams",
	"You are the power source",
	"Turn a violent genre non-violent",
	"An abandoned world",
	"1 minute to prepare",
	"Decay",
	"Side effects",
	"Fragile",
	"Outdated technology",
	"Ruins",
	"Momentum",
	"Automation",
	"Keep it alive",
	"Garden",
	"Connections",
	"Start with nothing",
	"Unconventional travel",
	"Side effects",
	"Small character, big enemies",
	"Factory",
	"Shelter",
	"One item, many uses",
	"Night is coming",
	"Making connections",
	"Isolation",
	"Duplication",
	"Mutation",
	"Low Tech",
	"Take one, leave the rest",
	"Evolve to survive",
	"Unconventional travel",
	"One rule",
	"Merge",
	"There is a spy among us",
	"Games that shouldn't be in first person done in first person",
	"Mutation",
	"Decay",
	"Making connections",
	"Reduce, reuse, recycle",
	"Rituals",
	"Only 3 colors",
	"Ancient mythology",
	"Isolation",
	"One item, many uses",
	"Small character, big enemies",
	"Evolve to survive",
	"Low Tech",
	"Extinction",
	"Duplication",
	"Take one, leave the rest",
	"Fragile",
	"Night is coming",
	"Edge of the world",
	"4 rooms",
	"Generations",
	"Build your weapon",
	"Déjà vu",
	"Every Input does two things",
	"Reflections",
	"Automation",
	"Factory",
	"Shelter",
	"Start with nothing",
	"Side effects",
	"Take care of the egg",
	"Overheating",
	"Only downgrades",
	"Alchemy",
	"Hide",
	"Colonization",
	"Prisoner",
	"Pollution",
	"Leave something behind",
	"You're not supposed to be here",
	"Seasons",
	"Start with nothing",
	"Unconventional travel",
	"Side effects",
	"Small character, big enemies",
	"Factory",
	"Shelter",
	"One item, many uses",
	"Night is coming",
	"Making connections",
	"Isolation",
	"Duplication",
	"Mutation",
	"Low Tech",
	"Take one, leave the rest",
	"Evolve to survive",
	"Unconventional travel",
	"One rule",
	"Merge",
	"There is a spy among us",
	"Games that shouldn't be in first person done in first person",
	"Mutation",
	"Decay",
	"Making connections",
	"Reduce, reuse, recycle",
	"Rituals",
	"Only 3 colors",
	"Ancient mythology",
	"Isolation",
	"One item, many uses",
	"Small character, big enemies",
	"Evolve to survive",
	"Low Tech",
	"Extinction",
	"Duplication",
	"Take one, leave the rest",
	"Fragile",
	"Night is coming",
	"Edge of the world",
	"4 rooms",
	"Generations",
	"Build your weapon",
	"Déjà vu",
	"Every Input does two things",
	"Reflections",
	"Automation",
	"Factory",
	"Shelter",
	"Start with nothing",
	"Side effects",
	"Take care of the egg",
	"Overheating",
	"Only downgrades",
	"Alchemy",
	"Hide",
	"Colonization",
	"Prisoner",
	"Pollution",
	"Leave something behind",
	"You're not supposed to be here",
	"Seasons",
	"Space exploration",
	"Everything has a price",
	"No upgrades, only downgrades",
	"Color changes everything",
	"Four elements",
	"Mutation",
	"Floating worlds",
	"Limited memory",
	"Your life is currency",
	"Symbiotic relationship",
	"Control the environment, not the player",
	"Old technology",
	"You have 30 seconds",
	"Unusual magic system",
	"You can't kill the enemies",
	"Parallel worlds",
	"Cards are your weapons",
	"The butterfly effect",
	"Only one enemy",
	"Light as a weapon",
	"One room",
	"Regular jobs, but in Space",
	"The environment is a weapon",
	"Change the genre of a classic video game",
	"Decay",
	"Stay in the dark",
	"Side effects",
	"Two-button game",
	"Time is the currency",
	"Risky powerups",
	"Permanent damage",
	"Don't let it escape",
	"Ridiculously overpowered",
	"You're the final boss",
	"Everything is a weapon",
	"You are a side character",
	"Shelter",
	"The more you die, the more the world dies",
	"You can't save them all",
	"You are the quest giver",
	"Contagious",
	"You control the enemies",
	"Alchemy",
	"Break the cycle",
	"Underground",
	"Nontraditional boss battles",
	"Two characters, one player",
	"Tiny town",
	"Limited memory",
	"Ridiculously overpowered",
	"Your life is currency",
	"Side effects",
	"Space exploration",
	"Change the genre of a classic video game",
	"Only one enemy",
	"Risky powerups",
	"Shelter",
	"Color changes everything",
	"Everything has a price",
	"Contagious",
	"Tiny town",
	"Mutation",
	"No upgrades, only downgrades",
	"Underground",
	"Automation",
	"Break the cycle",
	"Control the environment, not the player",
	"Each playthrough builds on the last",
	"Everything grows",
	"It only changes when you aren't looking",
	"Sacrifices must be made",
	"Absorb your enemies",
	"Darkness is your friend",
	"Don't trust the game",
	"Magic, but at what cost?",
	"Making connections",
	"One item, many uses",
	"Take one, leave one",
	"Two connected worlds",
	"Evolve",
	"You are what you eat",
	"Sacrifices must be made",
	"Everything grows",
	"Inputs are expensive",
	"1 vs 100",
	"Evolve",
	"Work with the enemy",
	"Transform your surroundings",
	"Symbiosis",
	"Two connected worlds",
	"Mistakes are permanent",
	"You only get one shot",
	"Nontraditional magic",
	"Self-replicating",
	"Nothing is permanent",
	"Symmetry",
	"you can only move or see, not both",
	"Magic, but at what cost?",
	"Alchemy",
	"Darkness is your friend",
	"Gameplay described by the title of a song",
	"Ancient technology",
	"60 seconds",
	"Fragile",
	"Corruption",
	"Making connections",
	"Floating islands",
	"Mythology",
	"Each playthrough builds on the last",
	"It's not a bug, it's a feature",
	"Decay",
	"Limited resources",
	"Useless superpowers",
	"Break the cycle",
	"Don't trust the game",
	"Absorb your enemies",
	"No killing allowed",
	"One item, many uses",
	"You are the princess waiting to be rescued in the castle",
	"Take one, leave one",
	"Scavenger",
	"Control the environment, not the player",
	"Indirect combat",
	"You're the final boss",
	"Permanent damage",
	"Automation",
	"Discovery",
	"It only changes when you aren't looking",
	"One bullet",
	"One minute",
	"Dying planet",
	"Ancient world",
	"Two points of view",
	"Fragile",
	"It's spreading",
	"Inconvenient super powers",
	"Start with nothing",
	"Running out of space",
	"Nothing is explained",
	"If you don't see it, it doesn't exist",
	"Color as a gameplay feature",
	"One enemy only",
	"Build a dungeon",
	"Control two things at once",
	"Light is key",
	"Evolve",
	"You start with everything and end with nothing",
	"Four elements",
	"Decay",
	"Use the enemies to win",
	"Duplication",
	"Expanding environment",
	"Safe in the dark",
	"Tiny machines",
	"3 Rules",
	"You can't control the player",
	"Alchemy & Magic",
	"Four-colour palette",
	"What you create you must destroy",
	"One of you is a traitor!",
	"It's not a bug, it's a feature",
	"You can't save them all",
	"You are the final boss",
	"Death is useful",
	"Find it, protect it",
	"Shadows",
	"Light is dangerous",
	"The game rules change after each failure",
	"Floating islands",
	"the more you use an action the worse it will perform",
	"You control the environment, not player",
	"Craft your own magic",
	"I have been here before",
	"You are not the main character",
	"Shelter",
	"Night is coming",
	"Running out of space",
	"Night is coming",
	"Decay",
	"Safe in the dark",
	"Fragile",
	"You are the final boss",
	"Evolve",
	"Light is key",
	"Death is useful",
	"Two points of view",
	"Dying planet",
	"It's spreading",
	"3 Rules",
	"One enemy only",
	"One minute",
	"You control the environment, not player",
	"You are the weapon",
	"A light in the dark",
	"Keep growing",
	"3 rules",
	"Shelter",
	"Unusual magic",
	"Color changes everything",
	"At the beginning there is nothing",
	"Combine 2 incompatible genres (e.g. turn based racing)",
	"You really shouldn't mix those",
	"Floating islands",
	"It spreads",
	"The environment changes you",
	"Fragile",
	"You are what you eat",
	"Self-replication",
	"You're doing that genre wrong (and that's okay)",
	"Fragile",
	"You can't save them all",
	"3 rules",
	"The world will end in five minutes",
	"One button, Two functions",
	"Labyrinth",
	"Unconventional movement",
	"Manipulate your enemies",
	"Tiny machines",
	"A hidden world",
	"Automation",
	"60 seconds",
	"Combine 2 incompatible genres (e.g. turn based racing)",
	"You don't play as the main character",
	"At the beginning there is nothing",
	"You are what you eat",
	"Shelter",
	"Inconvenient superpowers",
	"Keep growing",
	"Switching perspectives",
	"Signal lost",
	"One weapon, many purposes",
	"Color changes everything",
	"Shrinking world",
	"You control the scenario, not the character",
	"Control multiple characters",
	"You are being watched",
	"Don't stop moving",
	"If you can't see it, it doesn't exist",
	"You control the environment, not the character",
	"You really shouldn't mix those",
	"You are the weapon",
	"Déjà vu",
	"Learn from your enemies",
	"A light in the dark",
	"Floating islands",
	"Self-replication",
	"The environment changes you",
	"Same level, different challenges",
	"It spreads",
	"Progress will make you weaker",
	"Only one light source",
	"Death helps you",
	"Everything is a weapon",
	"Four elements",
	"Unusual magic",
	"Indirect player control",
	"Expanding",
	"One level, but constantly changing",
	"Primitive technology",
	"Only one bullet",
	"Shipwrecked",
	"Into the unknown",
	"Everything is connected",
	"Mutation",
	"Connection lost",
	"Inconvenient superpowers",
	"Labyrinth",
	"One minute",
	"Only three colors",
	"The moon",
	"Guns that don't shoot bullets",
	"System failure",
	"Floating islands",
	"You are not the main character",
	"A single resource",
	"Everything is a weapon",
	"Symmetry",
	"Strange combinations",
	"Planets",
	"Hidden world",
	"Strange side-effects",
	"Non-violent solutions",
	"Alchemy",
	"Limited space",
	"1-player splitscreen",
	"Start with nothing",
	"Death is useful",
	"Some assembly required",
	"You control the scenario, not the character",
	"Broken world",
	"Multiple perspectives",
	"Space exploration",
	"Tiny machines",
	"Momentum",
	"Day and night",
	"Reflection",
	"You can't save them all",
	"You can't see everything",
	"Evolve",
	"It's not a glitch, it's a feature",
	"Four elements",
	"Nothing is permanent",
	"Isolation",
	"The more you have, the worse it is",
	"Floating islands",
	"The more you have, the worse it is",
	"A single resource",
	"Limited space",
	"Expanding",
	"You are not the main character",
	"Tiny machines",
	"Only three colors",
	"Broken world",
	"Start with nothing",
	"You control the scenario, not the character",
	"One level, but constantly changing",
	"Death is useful",
	"One minute",
	"Into the unknown",
	"Everything is connected",
	"Signal lost",
	"Parallel worlds",
	"Moving fortress",
	"Running out of power",
	"You are alone",
	"Start with nothing",
	"Machines",
	"Running out of space",
	"On / Off",
	"Connections",
	"Protect it",
	"You are not the main character",
	"1 vs 100",
	"It spreads",
	"Different perspective",
	"1 HP",
	"Different perspective",
	"Running out of space",
	"Parallel worlds",
	"Life in a bottle",
	"It spreads",
	"Running out of time",
	"30 seconds",
	"Limited tools",
	"Invasion",
	"Mirror",
	"Limited visibility",
	"Endless night",
	"Magnetic",
	"You are not the main character",
	"Travelers",
	"Unconventional movement",
	"Connections",
	"Moving fortress",
	"You have to die",
	"Evolve",
	"You can't save them all",
	"Playing with fire",
	"One rule",
	"You are the weapon",
	"Underground life",
	"1 bullet",
	"Power-downs (no Power-ups)",
	"Start with nothing",
	"Running out of power",
	"Simple mechanics",
	"Control multiple characters",
	"You'll need a map",
	"Machines",
	"You are alone",
	"You can't move",
	"1 HP",
	"Signal lost",
	"On / Off",
	"Without explanation",
	"1 vs 100",
	"Spaceship",
	"One item, two actions",
	"Sound is a weapon",
	"Protect it",
	"You are the dungeon",
	"Minimal",
	"Two buttons",
	"Inconvenient superpowers",
	"Inconvenient Superpowers",
	"Start with Nothing",
	"Dark / Light",
	"One Tool, Many Uses",
	"Pausing has Consequences",
	"You control the game, not the player",
	"Explore the Unknown",
	"Strength in Numbers",
	"Nothing is Permanent",
	"A Small World",
	"Infectious",
	"One Time Use",
	"One Enemy",
	"30 Seconds",
	"Four Elements",
	"Unexpected Mechanics",
	"On / Off",
	"Everything has a Cost",
	"Save Yourself, Not the World",
	"You are the Bad Guy",
	"Connections",
	"Two Colors",
	"Limited Energy",
	"Evolve",
	"Very Important Object",
	"Time Manipulation",
	"Control Several Characters",
	"Rebuild",
	"Space Travel",
	"Parallel Dimensions",
	"You are Alone",
	"Fragile",
	"Island",
	"A World in the Skies",
	"Consequences",
	"Magnetism",
	"Strange World",
	"Death is only the Beginning",
	"Unconventional Movement",
	"Hive Mind",
	"Time is Power",
	"Expansion",
	"Limited Button Presses",
	"Creation and Destruction",
	"Playing with Fire",
	"Keep it Alive",
	"Illusions",
	"Reincarnation",
	"Dark / Light",
	"You control the game, not the player",
	"Parallel Dimensions",
	"Pausing has Consequences",
	"Keep it Alive",
	"Two Colors",
	"Island",
	"A World in the Skies",
	"You are Alone",
	"Inconvenient Superpowers",
	"On / Off",
	"Death is only the Beginning",
	"Start with Nothing",
	"One Tool, Many Uses",
	"Everything has a Cost",
	"A Small World",
	"One room",
	"Underground",
	"Only 5 minutes",
	"Control the environment not the characters",
	"Wait, are we the bad guys?",
	"Salvage and repair",
	"Nothing is permanent",
	"Running out of space",
	"Save yourself, not the world",
	"Isolation",
	"Into the unknown",
	"Upgrade yourself",
	"Leave something behind",
	"Chain reaction",
	"Small world",
	"Simplicity",
	"Isolation",
	"Chain reaction",
	"Time kills you",
	"Simplicity",
	"Escape the game",
	"Natural selection",
	"Your enemy is your weapon",
	"Control the environment not the characters",
	"Parallel worlds",
	"Indirect control",
	"Fix it",
	"Wait, are we the bad guys?",
	"Choose one",
	"Inconvenient superpowers",
	"Light and dark",
	"Fusion",
	"Underground",
	"The rules change as you play",
	"One resource",
	"Save yourself, not the world",
	"Leave something behind",
	"Assemble",
	"Get me out of here!",
	"Adaptation",
	"Two colors",
	"Artificial life",
	"Guardian",
	"Infinite loop",
	"One room",
	"Stronger together",
	"Surveillance",
	"Playing both sides",
	"Into the unknown",
	"Unconventional physics",
	"Nothing is permanent",
	"Time manipulation",
	"Apocalypse",
	"Alchemy",
	"Teleportation",
	"Upgrade yourself",
	"Salvage and repair",
	"Running out of space",
	"Weaponless",
	"Only 5 minutes",
	"Advancing technology",
	"Small world",
	"You are the projectile",
	"Afterlife"
]

const themeList = []

originalThemeList.forEach(_theme => {
	if (!themeList.some(_existingTheme => _existingTheme == _theme)) {
		themeList.push(_theme)
	}
})

function getRandomNumber(_max) {
	return Math.floor(Math.random() * (_max + 1))
}

function getRandomTheme(_count = 1) {
	const result = [];

	for (let i = 0; i < _count; i++) {
		let randomTheme
		console.log(`Count : ${i}`)

		while (randomTheme == undefined || result.some(_aaaa => _aaaa == randomTheme)) {
			const randomNumber = getRandomNumber(themeList.length - 1)
			randomTheme = themeList[randomNumber]
			console.log(`Random number: ${randomNumber}`)
			console.log(`Random theme: ${randomTheme}`)
		}

		result.push(randomTheme)
	}

	return result;
}

function addListElement(_content) {
	document.getElementById("theme_list").append(_content)
}

function createNewTheme() {
	const newLine = document.createElement("div")

	getRandomTheme(2).forEach(_theme => {
		const newTheme = document.createElement("span")
		newTheme.innerHTML = _theme
		newLine.append(newTheme)
	})

	addListElement(newLine)
}

function clearThemes() {
	document.getElementById("theme_list").innerHTML = '';

	const themeCountElement = document.createElement("div")
	themeCountElement.innerHTML = `Total theme list: ${themeList.length} theme(s) (themes Ludum Dare [37, 50])`
	addListElement(themeCountElement)
}

window.addEventListener('load', clearThemes)